package bruhcollective.itaysonlab.microapp.gamepage.ui

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.nestedscroll.nestedScroll
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import bruhcollective.itaysonlab.jetisteam.uikit.page.PageLayout
import bruhcollective.itaysonlab.jetisteam.util.SteamBbToMarkdown
import bruhcollective.itaysonlab.microapp.gamepage.ui.components.*
import com.halilibo.richtext.markdown.Markdown
import com.halilibo.richtext.ui.material3.Material3RichText

@OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun GamePageScreen(
    onBackClick: () -> Unit,
    viewModel: GamePageViewModel = hiltViewModel()
) {
    val topAppBarState = rememberTopAppBarState()
    val scrollBehavior = TopAppBarDefaults.pinnedScrollBehavior(state = topAppBarState)

    PageLayout(state = viewModel.state, onReload = viewModel::reload) { data ->
        Scaffold(
            topBar = {
                TopAppBar(
                    title = { data.fullDetails.name },
                    scrollBehavior = scrollBehavior,
                    colors = TopAppBarDefaults.smallTopAppBarColors(
                        containerColor = Color.Transparent,
                        actionIconContentColor = Color.White,
                    ),
                    navigationIcon = {
                        IconButton(onClick = onBackClick) {
                            Icon(imageVector = Icons.Rounded.ArrowBack, contentDescription = null)
                        }
                    }
                )
            }, modifier = Modifier
                .nestedScroll(scrollBehavior.nestedScrollConnection)
                .fillMaxSize()
        ) { innerPadding ->
            LazyColumn {
                item {
                    GamePageHeader(
                        background = data.headerBackgroundUrl,
                        backgroundBlurred = data.headerBackgroundAutogenerated,
                        logoUrl = data.logoUrl,
                        useTextLogo = data.logoUrlAbsent,
                        name = data.fullDetails.name
                    )
                }

                item {
                    GamePageInfo(
                        publishers = data.fullDetails.publishers,
                        developers = data.fullDetails.developers,
                        releaseDate = data.fullDetails.releaseDate
                    )
                }

                item {
                    Text(text = data.fullDetails.shortDescription, modifier = Modifier.padding(16.dp))
                }

                item {
                    GamePageTagList(
                        tags = data.tags,
                        genres = data.fullDetails.genres,
                        metaCritic = data.fullDetails.metacritic
                    )
                }

                item {
                    GamePageMediaContainer(
                        urls = remember(data.fullDetails) {
                            data.fullDetails.screenshots.map { it.thumbnail }
                        }
                    )
                }

                item {
                    CompositionLocalProvider(LocalContentColor provides MaterialTheme.colorScheme.onSurface) {
                        Material3RichText(modifier = Modifier.padding(16.dp)) {
                            Markdown(content = remember(data.fullDetails.fullDescription) {
                                SteamBbToMarkdown.prettifyHtml(data.fullDetails.fullDescription)
                            })
                        }
                    }
                }
            }
        }
    }
}